# Reglas de análisis estático para mantener un código limpio y consistente.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false            # Permitimos print() solo en pruebas/diagnóstico
    use_key_in_widget_constructors: true
    prefer_final_locals: true

analyzer:
  errors:
    # Tratar la documentación de APIs públicas como advertencia, no error.
    public_member_api_docs: ignore
  exclude:
    - "**/*.g.dart"
    - "build/**"
